module.exports = {
  FRIENDS_RECEIVED: "FRIENDS_RECEIVED",
  FRIEND_CREATED: "FRIEND_CREATED",
  REMOVE_FRIEND: "REMOVE_FRIEND",

  REQUESTS_RECEIVED: "REQUESTS_RECEIVED",
  FRIENDSHIP_APPROVED: "FRIENDSHIP_APPROVED",
  PEOPLE_RECEIVED: "PEOPLE_RECEIVED"
}
